const allProperties = [
  { id: 1, title: 'Casa Linda 1 dsfsd' },
  { id: 2, title: 'Casa Linda 1 sda' },
  { id: 3, title: 'Casa Linda 1dsd' },
  { id: 4, title: 'Casa Linda 1 ds' },
  { id: 5, title: 'Casa Linda 1' },
  { id: 6, title: 'Casa Linda 1ds' },
  { id: 7, title: 'Casa Linda 1vev' },
  { id: 8, title: 'Casa Linda 1veve' },
  { id: 9, title: 'Casa Linda 1vewerw' },
  { id: 10, title: 'Casa Linda 1ve' },
  { id: 11, title: 'Casa Linda 1ve' },
  { id: 12, title: 'Casa Linda 1rewr' },
  { id: 13, title: 'Casa Linda 1erw' },
  { id: 14, title: 'Casa Linda 1rwr' },
  { id: 15, title: 'Casa Linda 1erew' },
  { id: 16, title: 'Casa Linda 1rew' },
  { id: 17, title: 'Casa Linda 1 efe' },
  { id: 18, title: 'Casa Linda 1fef' },
  { id: 19, title: 'Casa Linda 1fe' },
  { id: 20, title: 'Casa Linda 1fe' },
  { id: 21, title: 'Casa Linda 1er' },
  { id: 22, title: 'Casa Linda 13' },
];
